[global]
disable = [
  "MD001",
  "MD013",
  "MD024",
  "MD025",
  "MD033",
  "MD036",
  "MD040",
  "MD041",
]
[MD046]
style = "fenced"

[MD049]
style = "asterisk"

[MD050]
style = "asterisk"

[MD060]
enabled = true
style = "compact"
